global:
  scrape_interval: 10s
  external_labels:
    site: prod
remote_write:
  - url: http://127.0.0.1:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30
scrape_configs:
  - job_name: 'prometheus.local'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'cms.local'
    scrape_interval: 5s
    static_configs:
      - targets: ['cms.local:9100']
  - job_name: 'nginx-cms.local' # Имя задания, которое будет отображаться в консоли Prometheus Server
    scrape_interval: 5s # Интервал опроса node_exporter
    static_configs:
      - targets: ['cms.local:9113'] # Точка подключения к node_exporter для сбора данных
  - job_name: 'phpfpm-cms.local' # Имя задания, которое будет отображаться в консоли Prometheus Server
    scrape_interval: 5s # Интервал опроса node_exporter
    static_configs:
      - targets: ['cms.local:9253'] # Точка подключения к node_exporter для сбора данных
  - job_name: 'postgres-cms.local' # Имя задания, которое будет отображаться в консоли Prometheus Server
    scrape_interval: 5s # Интервал опроса node_exporter
    static_configs:
      - targets: ['cms.local:9187'] # Точка подключения к node_exporter для сбора данных
  - job_name: 'joomla website availability'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://joomla.local       # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
